### ISSUE TITLE
Random Sizes of word

### ISSUE THREAD

**Issue by shantanug-cuelogic** [chrisrzhou/react-wordcloud#20] opened 2019-07-10 10:01 UTC
Hello !
I am integrating this library and my use case is  to show the words bigger which has more value. It is working fine for some cases but sometimes the the fontsize is more for words having less value then other. Is this what is expected or i need to configure something in options.

**Comment by chrisrzhou** [comment] 2019-09-09 06:10
Hi @shantanug-cuelogic, can you link me to a specific Codesandbox instance?  I need some steps to reproduce.

There are scenarios when the rendering is not ideal (e.g. words looking small even though the value is large, as you have mentioned).  This happens when the word itself is very long.  The `d3.cloud` layout takes into consideration both the size and value when deciding how to render the size of the word.  You might have to play around with `fontSizes` array to try to get the ideal setup.

Sorry if I can't help in your explicit example, but let me know if you can mitigate this somehow!

**Comment by chrisrzhou** [comment] 2019-09-12 05:18
Closing the issue for now since this is the underlying behavior of `d3.cloud` and there is no easy way but to customize `fontSizes` prop.

**Closed as completed by chrisrzhou** 2019-09-12 05:18 UTC
Labels: bug, wontfix
